server.port=8888
spring.application.name=config-server
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=native
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude-name=org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration,org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration,org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration
spring.cloud.config.server.native.search-locations=classpath:/shared-configs
